version: '3'
services:
  db:
    image: postgres:16-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=helha

  keycloak:
    image: keycloak/keycloak
    command: ["start-dev"]
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db/postgres?currentSchema=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=helha
      - KC_DB_SCHEMA=keycloak